/* tslint:disable */
require("./TeamLeadHub.module.css");
const styles = {
  toolTile: 'toolTile_dcad21e2',
  toolContentClose: 'toolContentClose_dcad21e2',
  toolViewerOpenFull: 'toolViewerOpenFull_dcad21e2',
  backLink: 'backLink_dcad21e2',
  hub: 'hub_dcad21e2',
  layout: 'layout_dcad21e2',
  mainColumn: 'mainColumn_dcad21e2',
  sidebar: 'sidebar_dcad21e2',
  weeklyRow: 'weeklyRow_dcad21e2',
  weeklyFocusCard: 'weeklyFocusCard_dcad21e2',
  weeklyFocusEyebrow: 'weeklyFocusEyebrow_dcad21e2',
  weeklyFocusTitle: 'weeklyFocusTitle_dcad21e2',
  weeklyFocusDate: 'weeklyFocusDate_dcad21e2',
  weeklyUpdatesCard: 'weeklyUpdatesCard_dcad21e2',
  weeklyUpdatesTitle: 'weeklyUpdatesTitle_dcad21e2',
  weeklyUpdatesList: 'weeklyUpdatesList_dcad21e2',
  toolViewerCard: 'toolViewerCard_dcad21e2',
  toolViewerHeader: 'toolViewerHeader_dcad21e2',
  toolViewerHeaderLeft: 'toolViewerHeaderLeft_dcad21e2',
  toolViewerHeaderIcon: 'toolViewerHeaderIcon_dcad21e2',
  toolViewerEyebrow: 'toolViewerEyebrow_dcad21e2',
  toolViewerTitle: 'toolViewerTitle_dcad21e2',
  toolContentActions: 'toolContentActions_dcad21e2',
  toolViewerBody: 'toolViewerBody_dcad21e2',
  toolViewerBodyActive: 'toolViewerBodyActive_dcad21e2',
  placeholderHint: 'placeholderHint_dcad21e2',
  toolContent: 'toolContent_dcad21e2',
  toolContentHeader: 'toolContentHeader_dcad21e2',
  toolContentTitleGroup: 'toolContentTitleGroup_dcad21e2',
  toolContentEyebrow: 'toolContentEyebrow_dcad21e2',
  toolContentTitle: 'toolContentTitle_dcad21e2',
  toolContentFrame: 'toolContentFrame_dcad21e2',
  toolContentComingSoon: 'toolContentComingSoon_dcad21e2',
  comingSoonIcon: 'comingSoonIcon_dcad21e2',
  comingSoonText: 'comingSoonText_dcad21e2',
  toolsPanel: 'toolsPanel_dcad21e2',
  panelTitle: 'panelTitle_dcad21e2',
  toolTileActive: 'toolTileActive_dcad21e2',
  toolIcon: 'toolIcon_dcad21e2',
  toolLabel: 'toolLabel_dcad21e2',
  toolsPanelMobile: 'toolsPanelMobile_dcad21e2',
  panelHeader: 'panelHeader_dcad21e2',
  toolsGrid: 'toolsGrid_dcad21e2',
  toolsPanelDesktop: 'toolsPanelDesktop_dcad21e2'
};

export default styles;
/* tslint:enable */