/* tslint:disable */
require("./TrainingHub.module.css");
const styles = {
  hubLink: 'hubLink_10ea3e3e',
  trainerDeptTile: 'trainerDeptTile_10ea3e3e',
  hub: 'hub_10ea3e3e',
  layout: 'layout_10ea3e3e',
  mainColumn: 'mainColumn_10ea3e3e',
  sidebar: 'sidebar_10ea3e3e',
  welcomeCard: 'welcomeCard_10ea3e3e',
  welcomeHeader: 'welcomeHeader_10ea3e3e',
  welcomeHeaderIcon: 'welcomeHeaderIcon_10ea3e3e',
  welcomeEyebrow: 'welcomeEyebrow_10ea3e3e',
  welcomeTitle: 'welcomeTitle_10ea3e3e',
  welcomeSubtitle: 'welcomeSubtitle_10ea3e3e',
  trainerHubCard: 'trainerHubCard_10ea3e3e',
  trainerHubHeader: 'trainerHubHeader_10ea3e3e',
  trainerHubEyebrow: 'trainerHubEyebrow_10ea3e3e',
  trainerHubTitle: 'trainerHubTitle_10ea3e3e',
  trainerHubSubtitle: 'trainerHubSubtitle_10ea3e3e',
  trainerHubGrid: 'trainerHubGrid_10ea3e3e',
  trainerDeptIcon: 'trainerDeptIcon_10ea3e3e',
  trainerDeptLabel: 'trainerDeptLabel_10ea3e3e',
  teamCard: 'teamCard_10ea3e3e',
  teamHeader: 'teamHeader_10ea3e3e',
  teamEyebrow: 'teamEyebrow_10ea3e3e',
  teamTitle: 'teamTitle_10ea3e3e',
  teamViewAll: 'teamViewAll_10ea3e3e',
  teamGrid: 'teamGrid_10ea3e3e',
  teamMember: 'teamMember_10ea3e3e',
  teamMemberTop: 'teamMemberTop_10ea3e3e',
  teamAvatar: 'teamAvatar_10ea3e3e',
  teamMemberInfo: 'teamMemberInfo_10ea3e3e',
  teamMemberName: 'teamMemberName_10ea3e3e',
  teamMemberRole: 'teamMemberRole_10ea3e3e',
  teamMemberFooter: 'teamMemberFooter_10ea3e3e',
  teamMemberScope: 'teamMemberScope_10ea3e3e',
  teamMemberContact: 'teamMemberContact_10ea3e3e',
  hubCard: 'hubCard_10ea3e3e',
  hubEyebrow: 'hubEyebrow_10ea3e3e',
  hubTitle: 'hubTitle_10ea3e3e',
  hubDescription: 'hubDescription_10ea3e3e'
};

export default styles;
/* tslint:enable */