/* tslint:disable */
require("./NotificationBell.module.css");
const styles = {
  bellWrapper: 'bellWrapper_2eccd54a',
  bellButton: 'bellButton_2eccd54a',
  badge: 'badge_2eccd54a',
  callout: 'callout_2eccd54a',
  calloutInner: 'calloutInner_2eccd54a',
  header: 'header_2eccd54a',
  headerTitle: 'headerTitle_2eccd54a',
  markAllBtn: 'markAllBtn_2eccd54a',
  list: 'list_2eccd54a',
  itemButton: 'itemButton_2eccd54a',
  itemUnread: 'itemUnread_2eccd54a',
  unreadDot: 'unreadDot_2eccd54a',
  unreadDotSpacer: 'unreadDotSpacer_2eccd54a',
  itemBody: 'itemBody_2eccd54a',
  itemTitle: 'itemTitle_2eccd54a',
  itemFields: 'itemFields_2eccd54a',
  itemMetaRow: 'itemMetaRow_2eccd54a',
  itemMeta: 'itemMeta_2eccd54a',
  viewDetailsHint: 'viewDetailsHint_2eccd54a',
  sourceTag: 'sourceTag_2eccd54a',
  sourceTagProtocolBook: 'sourceTagProtocolBook_2eccd54a',
  sourceTagInstructionBlock: 'sourceTagInstructionBlock_2eccd54a',
  empty: 'empty_2eccd54a',
  errorState: 'errorState_2eccd54a',
  loadingState: 'loadingState_2eccd54a',
  detailMeta: 'detailMeta_2eccd54a',
  detailMetaSeparator: 'detailMetaSeparator_2eccd54a',
  snapshotContent: 'snapshotContent_2eccd54a',
  snapshotSection: 'snapshotSection_2eccd54a',
  snapshotSectionLabeled: 'snapshotSectionLabeled_2eccd54a',
  snapshotLabel: 'snapshotLabel_2eccd54a',
  snapshotValue: 'snapshotValue_2eccd54a',
  snapshotEmpty: 'snapshotEmpty_2eccd54a',
  snapshotPlaceholder: 'snapshotPlaceholder_2eccd54a',
  diffWrapper: 'diffWrapper_2eccd54a',
  diffWasLine: 'diffWasLine_2eccd54a',
  diffNowLine: 'diffNowLine_2eccd54a',
  diffLineLabel: 'diffLineLabel_2eccd54a',
  diffLineContent: 'diffLineContent_2eccd54a',
  diffRemoved: 'diffRemoved_2eccd54a',
  diffAdded: 'diffAdded_2eccd54a',
  diffLoadingHint: 'diffLoadingHint_2eccd54a'
};

export default styles;
/* tslint:enable */