/* tslint:disable */
require("./Navigation.module.css");
const styles = {
  nav: 'nav_1beffd4f',
  navInner: 'navInner_1beffd4f',
  list: 'list_1beffd4f',
  listItem: 'listItem_1beffd4f',
  link: 'link_1beffd4f',
  linkActive: 'linkActive_1beffd4f',
  linkDisabled: 'linkDisabled_1beffd4f',
  homeLink: 'homeLink_1beffd4f',
  homeIcon: 'homeIcon_1beffd4f',
  dropdown: 'dropdown_1beffd4f',
  dropdownTitle: 'dropdownTitle_1beffd4f',
  dropdownTitleActive: 'dropdownTitleActive_1beffd4f',
  listItemActive: 'listItemActive_1beffd4f',
  chevron: 'chevron_1beffd4f',
  utilityBar: 'utilityBar_1beffd4f',
  searchBox: 'searchBox_1beffd4f',
  searchInputWrapper: 'searchInputWrapper_1beffd4f',
  searchIconInline: 'searchIconInline_1beffd4f',
  searchInput: 'searchInput_1beffd4f',
  searchClear: 'searchClear_1beffd4f',
  searchDropdown: 'searchDropdown_1beffd4f',
  searchResult: 'searchResult_1beffd4f',
  searchResultActive: 'searchResultActive_1beffd4f',
  searchResultName: 'searchResultName_1beffd4f',
  searchResultMeta: 'searchResultMeta_1beffd4f',
  searchResultBadge: 'searchResultBadge_1beffd4f',
  searchResultRoleBadge: 'searchResultRoleBadge_1beffd4f',
  searchNoResults: 'searchNoResults_1beffd4f',
  utilityIcon: 'utilityIcon_1beffd4f',
  hamburger: 'hamburger_1beffd4f',
  mobileDrawer: 'mobileDrawer_1beffd4f',
  mobileNavList: 'mobileNavList_1beffd4f',
  mobileNavLink: 'mobileNavLink_1beffd4f',
  mobileChevron: 'mobileChevron_1beffd4f',
  mobileNavLinkActive: 'mobileNavLinkActive_1beffd4f',
  mobileNavLinkLabel: 'mobileNavLinkLabel_1beffd4f',
  mobileSubList: 'mobileSubList_1beffd4f',
  mobileSubLink: 'mobileSubLink_1beffd4f',
  mobileNavLinkDisabled: 'mobileNavLinkDisabled_1beffd4f',
  mobileSubLinkDisabled: 'mobileSubLinkDisabled_1beffd4f',
  utilityBarWithSearch: 'utilityBarWithSearch_1beffd4f'
};

export default styles;
/* tslint:enable */